/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_test001_JNIUtil */

#ifndef _Included_com_jni_test001_JNIUtil
#define _Included_com_jni_test001_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_test001_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_1test001_JNIUtil_getWorld
  (JNIEnv *env, jobject obj){
    return env->NewStringUTF("Hello World 754");
}

#ifdef __cplusplus
}
#endif
#endif
